name          'KyleAnderson/nerve'
version       '0.0.1'
source        'https://github.com/solarkennedy/puppet-nerve'
author        'Kyle Anderson <kyle@xkyle.com>'
license       'Apache License, Version 2.0'
summary       'This puppet module installs and configures Nerve as part of Airbnb's SmartStack'
description   'This puppet module installs and configures Nerve as part of Airbnb's SmartStack'
project_page  'https://github.com/solarkennedy/puppet-nerve'

dependency 'puppetlabs/stdlib'
